#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Loading python Modules
module load eb
module load Miniconda2
module load R

#Activating virtual environment
echo "Loading virtual environment"
source activate qiime1

#Setting Temporary Directory
export TMPDIR=~/qiime_tmp

#principal coordainates Acido
echo "pcoaAcido"
time principal_coordinates.py -i beta_divAcido/ -o pcoaAcido/

#deactivating virtual environment
source deactivate

