#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Loading python Modules 
module load eb
module load Miniconda2

#Activating virtual environment 
echo "Loading virtual environment"
source activate qiime1

#Setting Temporary Directory
export TMPDIR=~/qiime_tmp

#Picking OTUs
echo "picking closed ref OTUs with SILVA database"
time pick_closed_reference_otus.py -i ~/2018_02_smb/demultiplex/seqs.fna -o ~/2018_02_smb/demultiplex/OTUs -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -t ~/SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt -a -O 16

#Decativating virtual Environment
source decativate 
